= Your own private AI Assistant
include::_attributes.adoc[]

It's 2025 after all. You thought we'd leave you stranded with just your own brain to work with? Of course not.

Now, you can obviously google things, and you could also ChatGPT things, but these scenarios are mission critical, and we can't afford any leaks around what the problems might be. You may have top-security clearance, but hosted services do not.

Therefore, we've provisioned for you an AI Assistant, running in your private project, and backed by OUR private version of Granite 3.1! You're welcome. But be careful: With Granite power, comes Granite responsibilities.

== Accessing your Assistant

1. From the main dashboard of OpenShift AI (https://rhods-dashboard-redhat-ods-applications.{openshift_cluster_ingress_domain}/[https://rhods-dashboard-redhat-ods-applications.{openshift_cluster_ingress_domain}/,window=_blank]) choose your private project (`{user}`)
2. In that project, click on the ... link.
3. Authenticate
4. Create a workspace
5. Confirm it's properly configured by asking it a random question

== Intended uses

We can't think of all the things YOU might want to leverage this for.
But we suggest the following might be useful ways of leveraging the AI assistant:

* explaining terms and concepts that may not be clear
* help with code analysis, explanation, modifications
* error and log messages analysis
* support with writing and developing notes
* brainstorming ideas, theories, and tests

