= Setup
include::_attributes.adoc[]

// Stars Classification in Spain

* The ASA (Amazing Space Agency) urgently requires your help! We are facing a critical situation, and only you and your team can save the day!
* A brand-new telescope called CAIx at the GranTeCan observatory (one of the link:https://en.wikipedia.org/wiki/Gran_Telescopio_Canarias[largest in the world]) has been launched.
* The CAIx telescope has captured hundreds of terabytes of data, but ASA cannot process all of it in time.
* The current challenges are as follows:
** All the experiments and notebooks required to process the data were stored on an old VM, which was accidentally deleted by an intern.
** Only one repository belonging to a former Data Scientist was salvaged from our link:https://github.com/rh-aiservices-bu/ai-mazing-race/tree/main/lab-materials/03[Git repository], but it contains multiple errors, and the Data Scientist left the Agency four months ago.
** We only have raw data stored in CSV files, but we lack the expertise to resolve the issue.

Your specific tasks are as follows:

* Fix the errors in the notebook.

** Use a workbench image that is suitable for running the notebook.

* Resolve the issues with the classification report and confusion matrix.

** Ensure precision and accuracy levels reach 98% or higher.

* Implement an automated solution for the notebook to run every 24 hours, 
every day of the week.

** Deploy the notebook using Data Science Pipelines and schedule it to run every 24 hours.
** Share your findings with the ASA team.
