= Execution
include::_attributes.adoc[]

Start by going to your Data Science project and make sure the `Mission workbench` have these settings:

* Image: `Standard Data Science`
* Size: `Small`

There will be three different tasks to perform to fulfil your mission. For each task, on the next page, you will find some hints to help you solve it. If you are stuck, solutions are also provided. They can also help you verify your own solution.

== Task 1 - The message

In the folder `lab-materials/04` you will find a Notebook file: `04-decrypt.ipynb` and a picture. That's everything the French government has provided you with. Retrieve the message...

== Task 2 - The environment

Now that you know what you need to retrieve the message, you must create an environment where the government can decrypt the message by themselves. Remember, the government will only be able to use the mouse to launch a Workbench, open the original Notebook, and run a cell. You really can't trust the government to install software on the fly.

== Task 3 - Setting everything up

Prepare your project to allow the government to decrypt the message. Just remember you are only a user in this environment, not an admin. So this may complicate things a bit...

Click to open the link:https://vclock.com/set-timer-for-15-minutes/[15-minute timer^]